baseURL = 'https://blog.neerajajithkumar.com'
languageCode = 'en-us'
title = 'today i learned'
theme = "cactus"
[params]

  colortheme = "dark" # dark, light, white, or classic
  dateFormat = "Jan 2006"
[[menu.main]]
name = "Home"
url = "https://neerajajithkumar.com/"
weight = 1

[[menu.main]]
name = "TIL"
url = "/posts"
weight = 2
  mainSectionTitle = "Blog"
