baseURL = 'https://blog.neerajajithkumar.com'
languageCode = 'en-us'
title = 'Blog Posts'
theme = "cactus"
[params]

  colortheme = "white" # dark, light, white, or classic
[[menu.main]]
name = "Home"
url = "https://neerajajithkumar.com/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2
  mainSectionTitle = "Blog"
